- Gemfile
- Gemfile.lock
- app/controllers/application_controller.rb
- app/models/user.rb
- config/environments/development.rb
- config/environments/test.rb
- config/initializers/gds_sso.rb
- db/migrate/20210310153334_create_users.rb
- db/schema.rb
- db/seeds.rb
- spec/models/user_spec.rb
- spec/spec_helper.rb
1. Re-run bundle on Linux, swapping out the darwin nokogiri for linux nokogiri
2. Clear `config.hosts` in dev mode, so it works in govuk-docker
3. Record branch coverage with simplecov
4. Set up the bullet gem: https://github.com/alphagov/govuk-account-manager-prototype/pull/616
5. Set up gds-sso
---
[Trello card](https://trello.com/c/ZeAKl2SM/651-set-up-a-new-app)
> A bunch of unrelated setup-related tweaks

- Gemfile.lock
- Jenkinsfile
Following these instructions here: https://docs.publishing.service.gov.uk/manual/setting-up-new-rails-app.html#configuring-the-app-for-jenkins
> Add a Jenkinsfile

- Jenkinsfile
The master/main branch changes have been merged.
> Use the default branch of govuk-jenkinslib

- spec/service_consumers/pact_helper.rb
> Fix pact branch & stub content store item

- Procfile
[Trello card](https://trello.com/c/8EadgviV/772-get-account-api-consuming-publishing-messages-from-rabbitmq)
> Add missing "bundle exec" to Procfile for rabbitmq listener

- app/controllers/saved_pages_controller.rb
- app/models/saved_page.rb
- db/migrate/20210601152044_add_public_updated_at_to_saved_page.rb
- db/schema.rb
- lib/message_queue_processor.rb
- spec/lib/message_queue_processor_spec.rb
- spec/requests/saved_pages_spec.rb
[Trello card](https://trello.com/c/om3hkQVZ/810-record-the-public-timestamp-for-saved-pages)
> Store the `public_updated_at` of saved pages

- Gemfile
- Gemfile.lock
- app/models/local_attribute.rb
- spec/factories/local_attribute_factory.rb
- spec/models/local_attribute_spec.rb
- spec/models/saved_page_spec.rb
- spec/spec_helper.rb
> Add validations to LocalAttribute to match db constraints

- docs/api.md
> Tweak API docs

- app/controllers/oidc_users_controller.rb
See also https://github.com/alphagov/email-alert-api/pull/1647
---
[Trello card](https://trello.com/c/Vzd8so2T/874-implement-designs-for-managing-your-email-notifications-via-the-account)
> Merge subscribers on conflict when changing address

- app/lib/oidc_client.rb
Some of the account-api endpoints have a pretty high variance in
response time.  Since the logic in account-api itself is not too
complex, my hunch is that this is the attribute service or account
manager being slow.  So, record some timer metrics to gather some more
evidence.
If it is the OIDC stuff being slow, then maybe we can add more
instances there.  And if it's not, well, this will still be useful
debugging data to have for future problems.
---
[Trello card](https://trello.com/c/UPXoxbRt/904-add-timing-metrics-to-account-api)
> Record timer metrics from OidcClient

- lib/tasks/reconcile_brexit_data.rake
> Add rake task to repair data for a small number of users

- docs/adr/001-flash-messages.md
[Rendered](https://github.com/alphagov/account-api/blob/msw/flash/docs/adr/001-flash-messages.md)
---
[Trello card](https://trello.com/c/I0ulYzeX/946-implement-a-way-to-use-flash-messages-for-accounty-things)
> Write up how we will do flash messages

- docs/adr/002-progressive-enhancement.md
[Rendered document](https://github.com/alphagov/account-api/blob/msw/adr-002/docs/adr/002-progressive-enhancement.md)
---
[Trello card](https://trello.com/c/jh8fjV7l/957-decide-on-computeedge-esi-or-frontend-javascript)
> Progressive Enhancement

- app/controllers/oidc_users_controller.rb
The `head`s here are already the last statements in their blocks.
> Remove some unnecessary `return`s

- app/lib/account_session.rb
- app/models/oidc_user.rb
- app/models/tombstone.rb
- db/migrate/20211026094310_create_tombstone.rb
- db/schema.rb
- spec/lib/account_session_spec.rb
- spec/models/oidc_user_spec.rb
- spec/models/tombstone_spec.rb
See commit messages for details.
---
[Trello card](https://trello.com/c/goXbVvpM/1113-record-when-a-user-is-deleted)
> Record when a user is destroyed, and end sessions for destroyed users

- lib/tasks/migration.rake
This prevents the user from logging in.
> Do not create a tombstone for merged users

- app/controllers/application_controller.rb
- app/controllers/concerns/authenticated_api_concern.rb
- app/controllers/internal/attributes_controller.rb
- app/controllers/internal/authentication_controller.rb
- app/controllers/internal/email_subscriptions_controller.rb
- app/controllers/internal/match_user_by_email_controller.rb
- app/controllers/internal/oidc_users_controller.rb
- app/controllers/internal/user_controller.rb
- app/controllers/internal_controller.rb
- app/controllers/personalisation/check_email_subscription_controller.rb
- app/controllers/personalisation_controller.rb
- config/application.rb
- config/environments/development.rb
- config/routes.rb
- spec/requests/check_email_subscription_spec.rb
> Refactor: move internal & personalisation controllers into separate modules, & only pull in cookies middleware in development mode

- Jenkinsfile
We've decided to merge these PRs in advance of the production migration.
---
[Trello card](https://trello.com/c/ZMFOPaCl/1176-upgrade-our-app-databases)
> Test against postgres 13 in CI

- app/lib/oidc_client.rb
- spec/lib/oidc_client_spec.rb
[Trello](https://trello.com/c/p3328fd0/1346-create-a-new-endpoint-to-support-auth)
[Merge after](https://github.com/alphagov/account-api/pull/405)
This will recieve an encoded JWT:
- Verify the signature (or throw an error)
- Then ask the LogoutToken class to validate the payload
Assuming all is well there it'll return a hash with a request_time, the
token as a JWT and the token itself. Mostly trying to keep pairty with
the id_token inclusion in the tokens! method. But I can see how those'd
be useful for debugging too.
Testing this is a bit of a pain. Discovery reaches out to the
.well-known endpoints of the Identity Provider. So I've stubbed those
out. I also skipped the JWS payloads and just used a secret that's a
string. The JSON::JWT code seems smart enough to work out what to do
with …
> Extend OidcClient to add a logout_token endpoint

- docs/adr/004-tombstone-records.md
Document the decision we've made to delete old Tombstone records
> ADR 004: Tombstone records

- app/controllers/application_controller.rb
- app/controllers/internal/authentication_controller.rb
- app/controllers/internal/oidc_users_controller.rb
- app/controllers/oidc_events_controller.rb
- app/lib/logout_token.rb
- app/models/logout_notice.rb
- app/models/oidc_user.rb
- config/routes.rb
- docs/api.md
- spec/lib/logout_token_spec.rb
- spec/lib/oidc_client_spec.rb
- spec/models/logout_notice_spec.rb
- spec/models/oidc_user_spec.rb
- spec/requests/back_channel_logout_spec.rb
- spec/requests/logout_notice_invalidation_spec.rb
- spec/support/helpers/oidc_client_helper.rb
Reverts alphagov/account-api#427
And sneaks in removing some parsing of JSON which doesn't seem needed!
> Revert "Revert "GUA-22 - Backchannel logout endpoint""

- app/lib/account_session.rb
- app/lib/user_attributes.rb
- app/models/attribute_definition.rb
- config/user_attributes.yml
- db/migrate/20220610101751_re_add_local_attribute_to_oidc_users.rb
- db/schema.rb
- spec/lib/account_session_spec.rb
- spec/models/attribute_definition_spec.rb
- spec/requests/attributes_spec.rb
- spec/requests/authentication_spec.rb
- spec/requests/email_subscriptions_spec.rb
- spec/service_consumers/pact_helper.rb
Reverts alphagov/account-api#433
> Revert "Remove attribute types and local attribute logic"

- .github/workflows/deploy.yaml
- .github/workflows/set-automatic-deploys.yaml
> Add Replatforming deployment action

- Dockerfile
> Dockerfile updates and mail gem workaround

- app/lib/oidc_client.rb
> Capture BackChannel Logout errors as sensitive exceptions so we can debug current problems

- app/controllers/oidc_events_controller.rb
- app/lib/oidc_client.rb
> Capture exception in the controller to examine exact parameters

- app/controllers/oidc_events_controller.rb
> Update wrong method call

- config/sidekiq.yml
- Somehow missed in the update to Sidekiq 7.
> Fix scheduled worker class names
