alphagov/account-api

Gemfile
Gemfile.lock
app/controllers/application_controller.rb
app/controllers/authentication_controller.rb
app/lib/oidc_client.rb
app/models/auth_request.rb
config/environments/development.rb
config/routes.rb
db/migrate/20210310134450_create_auth_requests.rb
db/schema.rb
spec/lib/oidc_client_spec.rb
spec/models/auth_request_spec.rb
spec/requests/authentication_controller_spec.rb
spec/spec_helper.rb
spec/support/helpers/oidc_client_helper.rb

This PR adds the three authentication endpoints from the RFC, at 95.41% line coverage (enough for continuous deployment).
The way the auth flow will work for the Transition Checker is:
1. finder-frontend calls `/api/oauth2/state` with the attributes, which returns a `state_id`
2. finder-frontend redirects the user to `/sign-in?state_id={...}&redirect_path={...}` (which is rendered by frontend)
3. frontend calls `/api/oauth2/sign-in` with the `state_id` and `redirect_path`, which returns an `auth_uri` and a `state`
4. frontend stores the `state` in the session (this is for CSRF protection) and redirects the user to the `auth_uri`
5. the user authenticates, and is sent to `/sign-in/callback?code={...}&state={...}` (which is rendered by frontend)
6. frontend checks that the `state` param …

Implement authentication endpoints

---

app/controllers/application_controller.rb
app/controllers/transition_checker_email_subscription_controller.rb
app/helpers/session_header_helper.rb
app/lib/oidc_client.rb
config/routes.rb
spec/helpers/session_header_helper_spec.rb
spec/requests/transition_checker_email_subscription_controller_spec.rb
spec/support/helpers/govuk_account_session_helper.rb

By putting these endpoints in this app, we can fully remove the OIDC /
OAuth logic from the Transition Checker.
The name of the controller is really specific because we've not yet
got a generic way to manage email subscriptions for multiple apps, and
will need to think about how to do that if it's something we want.
---
[Trello card](https://trello.com/c/N49KKdOW/666-move-transition-checker-email-management-from-finder-frontend-to-the-new-app)

Add endpoints to manage the Transition Checker email subscription 

---

app/controllers/attributes_controller.rb
app/lib/oidc_client.rb
config/brakeman.ignore
config/routes.rb
spec/requests/attributes_controller_spec.rb

Currently these just delegate to the govuk-attribute-service-prototype
running on the PaaS, but at some point soon we will begin storing
attributes in this app's database too.  We might migrate the
Transition Checker attributes, or we might just retire the checker -
that depends on how long it'll be staying around, which is a product
decision.
For the update endpoint, the attribute values are given as
JSON-encoded strings.  I think this is reasonable, because there isn't
really a standard for how complex nested data gets turned into HTTP
field data.  We can do the `to_json`ing in gds-api-adapters, so that
other apps don't need to worry about it.
---
[Trello card](https://trello.com/c/uRMyiEHZ/654-move-oauth-attribute-logic-from-the-transition-checker-to-the-new-app)

Add endpoints to manage attributes 

---

app/controllers/application_controller.rb
spec/requests/attributes_controller_spec.rb

The finder-frontend smokey tests picked this up, maybe it's sending a
weird cookie value?  In any case, this header value ultimately comes
from a user-controlled input, so we shouldn't throw an internal server
error if the format isn't what we expect.
---
Also we don't have sentry set up properly for account-api (no sentry_dsn in the env), fixing that is the next thing to do.

Return 401 if an invalid account header is given

---

app/controllers/attributes_controller.rb

Currently, if the access token expires and gets refreshed while
fetching attributes, we return the old tokens instead of the new ones.

Return the up-to-date account session header with the attributes

---

config/initializers/govuk_error.rb

As part of the steps to set up sentry for a new GOV.UK repository.
See documentation here: https://docs.publishing.service.gov.uk/manual/sentry.html#how-sentry-is-integrated-on-govuk

Add GOV.UK Error initalizer

---

.gitignore
Gemfile
Gemfile.lock
app/controllers/authentication_controller.rb
app/models/auth_request.rb
lib/tasks/pact.rake
spec/service_consumers/pact_helper.rb

This is step 2 of the [Writing Pact tests](https://docs.publishing.service.gov.uk/manual/pact-broker.html#writing-pact-tests) docs, see also https://github.com/alphagov/gds-api-adapters/pull/1043.
---
Pact provider configuration specifies which contracts are
honoured (currently only gds-api-adapters) and defines a set of
"provider states", which are a sort of precondition that the consumer
tests expect.
A Pact test has two parts:
1. The consumer test, which specifies which provider state is
expected, gives the request, and an expected response.
2. The provider configuration, which defines all of the provider
states.
There are no actual tests in the provider: rather, the requests
defined by the consumer tests are run against the provider, and pact
checks that the responses match.
--- …

Write Pact provider configuration

---

spec/requests/attributes_controller_spec.rb
spec/requests/authentication_controller_spec.rb
spec/requests/transition_checker_email_subscription_controller_spec.rb

By default, Rails request specs send parameters as
application/x-www-form-urlencoded, but this has two problems:
1. gds-api-adapters sends JSON requests, so sending form data means
our test & production behaviours are very different.
2. form-data is bad at encoding complex nested data (or even just
numbers - which are decoded as strings), so we limit our app to only
what form-data supports.
A concrete problem caused by (2) is that the PATCH attributes endpoint
requires attribute values to be passed in as strings of JSON-encoded
data.  This is weird and confusing, and not at all like publishing-api
or email-alert-api.  It would be good to fix that, but first we need
these tests to do the right thing.
By instead sending JSON data in our tests (which publishing-api does
in its tests), we …

Send application/json requests in the request specs

---

Gemfile
Rakefile
lib/tasks/pact.rake
spec/service_consumers/pact_helper.rb

This is step 4 of the [Writing Pact tests](https://docs.publishing.service.gov.uk/manual/pact-broker.html#writing-pact-tests) docs.
---
The gds-api-adapters contract is now being published to the
pact-broker, so these tests will pass.
---
[Trello card](https://trello.com/c/OcRffYwv/674-set-up-pact-tests-for-our-account-api-app)

Run Pact tests as part of the default rake task

---

app/controllers/attributes_controller.rb
app/lib/oidc_client.rb
spec/requests/attributes_controller_spec.rb

The create-state endpoint accepts plain JSON, rather than encoded
values.  This commit makes the update-attributes endpoint also accept
plain JSON, to be consistent.
To support backwards compatibility, encoded attribute values are also
accepted.  If all of the attribute values are JSON strings, then the
assumption is made that they have been encoded by the sender.  In
practice, this is the case, because gds-api-adapters is the only thing
which uses this endpoint so far and that's what it does.
After this has been deployed we can:
1. update gds-api-adapters to *not* encode the attribute values
2. deploy a finder-frontend with the updated gds-api-adapters
3. remove the backwards compatibility code here
Moving to accept plain JSON values (rather than strings of encoded
values) makes this …

Allow non-encoded attribute values

---

app/controllers/attributes_controller.rb
app/lib/oidc_client.rb
spec/requests/attributes_controller_spec.rb

This removes the compatibility code introduced in c7c9a5b, as a new
release of gds-api-adapters has been made (and deployed) which
switches to the new encoding.
---
[Trello card](https://trello.com/c/E5J5kzNP/679-remove-the-redundant-json-encoding-of-attribute-values-in-account-api)

Remove support for giving attributes as JSON strings

---

app/controllers/authentication_controller.rb

These endpoints don't let you do anything nefarious, so they don't
need auth to access.  Unprotecting these means we don't need to set up
a bearer token for frontend.

Do not require a bearer token for /api/oauth2/{sign-in,callback}

---

README.md
docs/api.md

The README is shorter than our Account Manager or Attribute Service apps, eg it doesn't have detailed set-up documentation.
Our GOV.UK READMEs have been standardising on a fairly terse format[(1)][][(2)][][(3)][] which I've copied.  In particular, there are no specific GOV.UK Docker commands referenced, I asked why on Slack and the thinking is that it makes GOV.UK Docker seem more magical than it is, and makes people think that they have to use GOV.UK Docker to run our apps, when really it's nothing more than a convenient shortcut.
The API documentation is inspired by [publishing-api][] and [router-api][].
[(1)]: https://github.com/alphagov/imminence
[(2)]: https://github.com/alphagov/router-api
[(3)]: https://github.com/alphagov/search-api
[publishing-api]: …

Flesh out README & add API docs

---

app/lib/oidc_client.rb
app/models/auth_request.rb

We're logging people in via /transition-check/login/callback currently, whoops.  Well, the fact that that has worked flawlessly just shows that we did the migration without breaking compatibility anywhere.

Use correct callback path

---

app/controllers/application_controller.rb

[Trello ticket][1]
In [frontend#2668][2] we worked out that Rails makes request headers available as
```
request.headers["HTTP_" + header_name.gsub(/-/,"_").upcase]
```
So in particular, our header is available at
```
request.headers["HTTP_GOVUK_ACCOUNT_SESSION"]
```
However, account-api has code to look up the header under a different name, because we weren't previously sure of the correct behaviour.
Now that we know what the correct behaviour is, the code for the incorrect case is redundant and can be removed.
[1]: https://trello.com/c/6GWYTVMM/681-remove-the-redundant-header-logic-in-finder-frontend-and-account-api
[2]: https://github.com/alphagov/frontend/pull/2668
⚠️ This repo is Continuously Deployed: make sure you [follow the …

Amend Rails session headers

---

app/controllers/attributes_controller.rb
app/controllers/authentication_controller.rb
app/controllers/transition_checker_email_subscription_controller.rb
app/helpers/session_header_helper.rb
app/lib/session_encryptor.rb
spec/helpers/session_header_helper_spec.rb
spec/lib/session_encryptor_spec.rb
spec/requests/authentication_controller_spec.rb
spec/service_consumers/pact_helper.rb

This should be deployed after the change to the account manager, as it
throws an error if the expected level_of_authentication parameter
isn't returned.
The use of LOWEST_LEVEL_OF_AUTHENTICATION in the SessionHeaderHelper
means that current sessions will be upgraded to level0 sessions.  This
won't be enough to use the Transition Checker, so they will end up
needing to reauthenticate, but it is enough to use the bookmark
experiment.
---
[Trello card](https://trello.com/c/yCLEBvxW/714-store-the-level-of-authentication-in-the-users-session)

Store the level of authentication in the session 

---

spec/spec_helper.rb

Some tests require a User to be present in the database. We create a
Test User in the seeds file but this is not automatically executed
before running the tests.
This config change populates the test database with seed data before
running tests so that the Test User is present.

Load seed data before tests

---

app/controllers/application_controller.rb
app/controllers/attributes_controller.rb
app/controllers/transition_checker_email_subscription_controller.rb
app/lib/user_attributes.rb
config/locales/errors.en.yml
config/user_attributes.yml
docs/api.md
spec/fixtures/user_attributes.yml
spec/lib/user_attributes_spec.rb
spec/requests/attributes_controller_spec.rb
spec/service_consumers/pact_helper.rb

This PR adds a config file holding attribute details, recording whether an attribute is stored locally or not, and adds validation to the AttributesController to reject unknown attributes.
I've also chosen to return a rejection error as an [RFC 7807 "Problem Detail" object](https://tools.ietf.org/html/rfc7807) because
1. we'll need to return some sort of structured error when we implement levels-of-authentication (to communicate back to the caller which LoA to reauthenticate the user at), and
2. it emphasises having online documentation for each distinct error type, which I think is really nice.
This PR isn't a proposal to standardise GOV.UK on using the RFC; but it would be good to be consistent within this one app at least.
---
[Trello …

Validate attributes and flag where they're stored

---

config/routes.rb
docs/api.md

govuk-puppet and govuk-aws have now been updated to only use the new
routes, so the old one is no longer needed.
See RFC 141 for more information.
---
[Trello card](https://trello.com/c/tl6RV1el/723-improve-govuk-healthchecks)

Remove legacy /healthcheck route

---

app/controllers/authentication_controller.rb
app/lib/account_session.rb
app/lib/oidc_client.rb
spec/lib/account_session_spec.rb
spec/requests/authentication_controller_spec.rb
spec/service_consumers/pact_helper.rb
spec/support/helpers/govuk_account_session_helper.rb
spec/support/helpers/oidc_client_helper.rb

When we start storing information in the account-api database, like
attributes or saved pages, we'll need an identifier to save them
under.  In preparation, this PR stores the user ID from the OIDC ID
Token in the session.
To upgrade existing sessions, the OIDC UserInfo endpoint is called to
fetch the ID.

Store the user ID in the session

---

app/lib/account_session.rb
spec/lib/account_session_spec.rb

If a session is sufficiently old, it may have expired tokens in it,
which cause the UserInfo request to fail.
Elsewhere in the app we catch the OAuth failure and return a 401
response (logging the user out) so, to be consistent with that, if the
user's session has expired tokens then log them out.

Return nil when a session has expired tokens and cannot fetch the ID

---

app/controllers/attributes_controller.rb
app/lib/account_session.rb
app/lib/api_error/level_of_authentication_too_low.rb
app/lib/api_error/unknown_attribute_names.rb
app/lib/level_of_authentication.rb
app/lib/user_attributes.rb
config/application.rb
config/locales/errors.en.yml
config/user_attributes.yml
docs/api.md
spec/fixtures/user_attributes.yml
spec/lib/user_attributes_spec.rb
spec/requests/attributes_controller_spec.rb
spec/service_consumers/pact_helper.rb

We can't switch this feature on until we have a way to authenticate a user to a specific level (there's a separate card for that) and then update finder-frontend to gracefully handle 403 errors.
Something I'm not entirely satisfied with in this PR is how the level of authentication stored in the session is a string, but really for comparison purposes we want an integer:
- Strings are good because it means that we're going to be using the same level names as Digital Identity, reducing the potential for confusion.
- Integers are good because we need a total ordering, which ideally is pretty efficient to compute, on the levels.
Having both is perhaps not so good, but I think the advantage of keeping around the original level in the session is good, because it means that if Digital Identity …

Enforce levels of authentication, gated behind a feature flag

---

app/controllers/application_controller.rb
app/controllers/attributes_controller.rb
app/controllers/concerns/authenticated_api_concern.rb
app/controllers/transition_checker_email_subscription_controller.rb

All authenticated APIs need to respond to an OAuth failure with a
401 (because it means the user's session is invalid) and to include
the serialised session identifier in the response body.
Doing that in each controller method results in a lot of duplication,
and also confusion, as logic like this is subtly wrong:
render json: {
govuk_account_session: @govuk_account_session.serialise,
foo: @govuk_account_session.go_something_oauthy,
}
As the serialisation needs to happen *after* any other calls.

Create a concern to handle common API functionality

---

app/controllers/authentication_controller.rb
app/lib/level_of_authentication.rb
app/lib/oidc_client.rb
docs/api.md
spec/lib/oidc_client_spec.rb

Since levels of authentication are disabled in the account manager currently, passing `level0` authenticates the user to `level1`.  So there is no change in behaviour yet.  But that will change in a few sprints time, so we'll also need to change finder-frontend to request `level1`.
Defaulting to `level0` seems sensible, as otherwise we'll end up with users who sign up at `level0` to save some pages but then, when they click "Sign In" in the header, are prompted to set up MFA.
---
[Trello card](https://trello.com/c/qGMyYZ51/715-implement-requesting-a-specific-level-of-authentication-from-the-account-manager)

Allow authenticating at a specific level

---

app/controllers/attributes/names_controller.rb
config/routes.rb
docs/api.md
spec/requests/attributes/names_controller_spec.rb

This endpoint allows querying if the user has a value stored for an
attribute, without returning the value.
It is very similar to `/api/attributes`, with the difference
that it only returns the name of the attribute instead of the name and
the value.
Trello card: https://trello.com/c/e7JQlXx9/710-add-an-endpoint-to-account-api-to-check-if-an-attribute-is-defined

Add `/api/attributes/names` endpoint

---

app/controllers/transition_checker_email_subscription_controller.rb
spec/requests/transition_checker_email_subscription_controller_spec.rb

The email subscription is kind of separate to the transition checker
state attribute, but also kind of tied to it, so it should have the
same access restrictions.
---
[Trello card](https://trello.com/c/G2uYUDuz/716-check-the-level-of-authentication-when-using-attributes-in-the-account-api)

Check permissions in the transition email controller

---

app/controllers/attributes/names_controller.rb
app/controllers/attributes_controller.rb
app/lib/account_session.rb
app/models/local_attribute.rb
app/models/oidc_user.rb
config/environments/test.rb
db/migrate/20210429121634_create_oidc_users.rb
db/migrate/20210429123551_create_local_attributes.rb
db/schema.rb
spec/fixtures/user_attributes.yml
spec/lib/account_session_spec.rb
spec/requests/attributes/names_controller_spec.rb
spec/requests/attributes_controller_spec.rb

We don't have any of these defined in the config file yet, so this code is essentially dead, but we will do when we start to work on the location experiment.
I decided to create an `OidcUser` model, which the `LocalAttribute`s are connected to, rather than just store the subject identifier in the `LocalAttribute`s directly, because this approach means that if subject identifiers change (which they almost certainly will do when we migrate from our OIDC provider to Digital Identity's) we only have one record per user to update.

Implement support for local attributes

---

app/controllers/concerns/authenticated_api_concern.rb

This section expects that the Bearer token will always arrive via a
header, however on development we put it in a cookie.
This adds a short method that conditionally reads from there if you are
on dev.

Take session from cookie when on development

---

app/lib/account_session.rb
spec/lib/account_session_spec.rb

By default upsert_all does not change the updated_at timestamp.  This
is fine if nothing has actually changed (eg, saving a duplicate page);
but in general saving an attribute value *is* a change, and so we want
the timestamp to change.

Set the updated_at time when storing new local attribute values

---

spec/requests/attributes/names_spec.rb
spec/requests/attributes_spec.rb
spec/requests/authentication_spec.rb
spec/requests/transition_checker_email_subscription_spec.rb

These have always been request specs, because they're in spec/requests
and we have `config.infer_spec_type_from_file_location!`
The rspec docs[1] show that request spec files should be called
"`<thing>_spec.rb`"; not "`<thing>_controller_spec.rb`" or
"`<thing>_request_spec.rb`", and should have a string name for the
top-level `describe` rather than a class name.
[1] https://relishapp.com/rspec/rspec-rails/docs/request-specs/request-spec

Fix naming convention for request specs

---

app/controllers/saved_pages_controller.rb
app/lib/api_error/cannot_save_page.rb
app/models/oidc_user.rb
app/models/saved_page.rb
config/locales/errors.en.yml
config/routes.rb
db/migrate/20210512111851_create_saved_pages.rb
db/schema.rb
docs/api.md
spec/factories/oidc_user_factory.rb
spec/factories/saved_page_factory.rb
spec/models/saved_page_spec.rb
spec/requests/saved_pages_spec.rb
spec/service_consumers/pact_helper.rb

[Trello card](https://trello.com/c/OvsvoWsO/766-implement-an-api-to-save-a-page-unsave-a-page-check-if-a-page-is-saved-and-return-the-list-of-saved-pages)
Also relevant: [gds-api-adapters#1067](https://github.com/alphagov/gds-api-adapters/pull/1067)
Add save page endpoints allowing an authenticated user to get an index of all their saved pages, as well ass add, delete or query a single saved page.

Save a page

---

Gemfile
Gemfile.lock
app/lib/oidc_client.rb
config/environments/production.rb
config/routes.rb
spec/service_consumers/pact_helper.rb
spec/support/helpers/oidc_client_helper.rb

We use OIDC discovery to avoid hard-coding things like URLs or keys in
this app.  This method makes an HTTP request to the Identity
Provider (govuk-account-manager-prototype) and then validates the
response.  But this response changes very infrequently, so this is
adding an unnecessary (and slow) network hop to almost every
account-api response.
This is most visible in the auth endpoint which, despite only
generating a URL, commonly takes 150ms because it's got this extra
request and validation going on, but it impacts the attribute and
Transition Checker email endpoints too.
---
[Trello card](https://trello.com/c/F4q6raJf/785-cache-oidc-discovery-response)

Cache the OIDC discovery response

---

Gemfile
Gemfile.lock
app/controllers/saved_pages_controller.rb
app/models/saved_page.rb
db/migrate/20210521080408_add_content_store_data_to_saved_page.rb
db/schema.rb
docs/api.md
spec/factories/saved_page_factory.rb
spec/models/saved_page_spec.rb
spec/requests/saved_pages_spec.rb

We'll need the content ID to handle publishing updates, as not all of
these have a base path (eg, a "vanish" update just specifies the
content ID).  So we can fetch this when the user saves a page (and
throw an error if the content item doesn't exist, rather than let them
save a non-existent page), and use it later in the message queue
consumer.
If the content item doesn't exist, return a 404.  If it does exist but
has been redirected or marked "gone", then return a 410.  I decided to
go for this over following the redirect automatically, as a redirected
page shouldn't render a save button on the original URL, it should
redirect the original URL.
We're likely to want page titles on the page which lists a user's
saved pages, so I've pulled that in here too.
---
[Trello …

Fetch content ID & title when saving a page

---

Gemfile
Gemfile.lock
Procfile
lib/message_queue_processor.rb
lib/tasks/message_queue.rake
spec/lib/message_queue_processor_spec.rb

For "gone" notifications, redirect if there is an alternative path or
delete the saved page if not.
For "redirect" notifications, redirect if there is a matching
redirect (including gracefully handling prefix redirects) or delete
the saved page if not.
For "vanish" notifications, delete the saved page.
For other notifications, update the saved information.
See also https://github.com/alphagov/govuk-puppet/pull/11111
---
[Trello card](https://trello.com/c/8EadgviV/772-get-account-api-consuming-publishing-messages-from-rabbitmq)

Implement the message queue processor

---

spec/service_consumers/pact_helper.rb
spec/support/helpers/govuk_account_session_helper.rb

This reduces a little code duplication between Pact and RSpec.

Re-use RSpec helpers in Pact helper

---

lib/message_queue_processor.rb
spec/lib/message_queue_processor_spec.rb

There is a small list (somewhere) of other government websites which
our content items can redirect to (e.g., www.justice.gov.uk).
Ultimately how to handle this is a design question but for now, for
the sake of getting a rough version of saved-page updating up and
running, just delete pages where the redirect target is not a genuine
GOV.UK content item.

Handle redirects where the target content item does not exist

---

app/lib/account_session.rb
app/lib/user_attributes.rb
config/user_attributes.yml
spec/fixtures/user_attributes.yml
spec/lib/account_session_spec.rb
spec/lib/user_attributes_spec.rb

At some point, we'll move the "Your Account" page from the
account-manager and onto GOV.UK proper (www.gov.uk/account ?).  When
that happens, this account-api will the only user of the
transition_checker_state attribute.
So to improve performance, we'd like to migrate the attribute from the
attribute-service into this app's database.  But we don't want to have
any downtime, so we can't go for the simple approach of:
1. Block updates to the attribute
2. Dump the attribute-service database
3. Import the attribute-service database into the account-api
4. Unblock updates to the attribute
As while the dump&import happens users won't be able to make changes.
Instead we want an online approach, which this commit enables:
1. Get account-api persisting transition_checker_state both
locally *and* …

Cache transition_checker_state locally

---

app/controllers/attributes_controller.rb
app/lib/account_session.rb
app/lib/api_error/unwritable_attributes.rb
app/lib/oidc_client.rb
app/lib/user_attributes.rb
config/locales/errors.en.yml
config/user_attributes.yml
docs/api.md
spec/fixtures/user_attributes.yml
spec/lib/oidc_client_spec.rb
spec/lib/user_attributes_spec.rb
spec/requests/attributes_spec.rb

This is so we can show the user's email address & prompt them to verify it on the account home page, which is going to move from the account manager to GOV.UK.
See commit messages for details.
---
[Trello card](https://trello.com/c/lIDQNATi/813-implement-the-govuk-account-home-page)

Refactor config code a little, add a notion of unwritable attributes, and make `email` and `email_verified` available

---

app/lib/account_session.rb
spec/lib/account_session_spec.rb

Attributes are non-nil: getting a nil from the remote means that the
attribute is unset, and so we shouldn't try to store it.
---
[Sentry error](https://sentry.io/organizations/govuk/issues/2430637572/)

Do not try to cache unset remote attributes

---

app/controllers/attributes_controller.rb
app/controllers/transition_checker_email_subscription_controller.rb
app/lib/account_session.rb
config/application.rb
docs/api.md
spec/lib/account_session_spec.rb
spec/requests/attributes_spec.rb
spec/requests/transition_checker_email_subscription_spec.rb
spec/service_consumers/pact_helper.rb

We've not yet enabled the ability to log in or register at level0 in
the account manager, so this won't impose any visible changes for
users who have logged in since late April.  Users who logged in before
then and still have a live session will be prompted to reauthenticate
when they next use the Transition Checker.
---
[Trello card](https://trello.com/c/6C8UdVFG/815-enforce-levels-of-authentication-in-production)

Enforce levels of authentication & remove support for legacy base64 sessions

---

app/models/auth_request.rb
app/models/saved_page.rb
app/validators/absolute_path_validator.rb

We had the same logic implemented differently in two places.  This commit adds a validator which both models use.

Remove duplication of absolute path validation

---

Gemfile
Gemfile.lock
app/lib/oidc_client.rb
config/secrets.yml
spec/service_consumers/pact_helper.rb
spec/spec_helper.rb

These aren't passed as parameters anywhere, and by putting these in
secrets.yml we can give them default values in dev and test, meaning
we don't need to set them with ClimateControl in our tests.
Also remove the `provider_uri` parameter from `OidcClient` because we
don't set that anywhere.

Put OAuth env vars in secrets.yml

---

app/controllers/user_controller.rb
config/routes.rb
docs/api.md
spec/requests/user_spec.rb
spec/service_consumers/pact_helper.rb

This provides all the data needed for the new `/account/home` page, so
we can render that with a single request to account-api rather than
needing to make at least three separate requests to: get some
attributes, check other attributes, and check saved pages.
---
[Trello card](https://trello.com/c/lIDQNATi/813-implement-the-govuk-account-home-page)

Add an API endpoint for getting batch user information

---

app/lib/account_session.rb

There's no need to do a database query every time this is used.

Cache the AccountSession.user value

---

config/routes.rb

Underscores in URLs are a bit weird.  To be consistent with other
paths, let's use hyphens!

Use "saved-pages" as route, not "saved_pages"

---

app/controllers/application_controller.rb
app/controllers/oidc_users_controller.rb
app/lib/account_session.rb
app/models/oidc_user.rb
config/initializers/gds_sso.rb
config/routes.rb
db/seeds.rb
spec/lib/account_session_spec.rb
spec/requests/authentication_spec.rb
spec/requests/oidc_users_spec.rb

I've called this `/api/oidc-users`, rather than using the existing
`/api/user`, because this endpoint feels pretty different to
`/api/user`:
- `/api/user` is for the user's profile details as used on GOV.UK
- the new endpoint is for the identity provider to update special
details (currently email)
They're both about the user, but through different lenses: the user as
seen on GOV.UK, and the user as managed by the OIDC service.  Hence,
`/api/oidc-users`.
You'll need to re-seed your database after pulling this change.
---
[Trello card](https://trello.com/c/UD2IR18h/830-make-account-manager-tell-account-api-about-email-address-changes)

Add an endpoint to update a user's email by subject identifier

---

spec/models/auth_request_spec.rb
spec/requests/authentication_spec.rb

Querystrings are needed when clicking the sign-in link from the header
on transition checker pages, as the current answers are in the
querystring.
This test would have prevented the bug introduced by #97.

Add tests for using a querystring in the auth redirect_path

---

app/models/local_attribute.rb
spec/models/local_attribute_spec.rb

We want to forbid nils, but false is a totally acceptable value to
have.  In particular, this forbids an `email_verified` value of
`false`.
---
[Trello card](https://trello.com/c/yzVmdrzw/829-add-rest-api-for-email-subscriptions-to-account-api)

Allow "false" as an attribute value

---

config/user_attributes.yml

Now that account-manager is telling account-api when a user updates
their email address, we know that the value in the account-api
database is up to date, so we don't need to fetch it from the remote.
---
[Trello card](https://trello.com/c/UD2IR18h/830-make-account-manager-tell-account-api-about-email-address-changes)

Mark email attributes "cached"

---

spec/lib/oidc_client_spec.rb
spec/requests/attributes/names_spec.rb
spec/requests/attributes_spec.rb
spec/requests/user_spec.rb
spec/service_consumers/pact_helper.rb
spec/support/helpers/oidc_client_helper.rb

Our API coverage looks pretty good, it's really only the `redirect_path` of the auth controller and the `page_path` of the saved pages controller where we're passing something which could directly come from user input.  And those have good coverage now.
I shuffled around the OIDC helpers a bit, merging two single-use methods into the file which needed them and adding a couple of new methods for stubbing remote attribute requests.
---
[Trello card](https://trello.com/c/siLdMmuu/848-review-api-tests-for-missing-coverage)

Reorganise OIDC spec helpers a bit

---

app/models/auth_request.rb
app/models/oidc_user.rb
app/models/saved_page.rb
app/validators/absolute_path_validator.rb
app/validators/absolute_path_with_query_string_validator.rb
spec/factories/auth_request_factory.rb
spec/models/auth_request_spec.rb
spec/models/oidc_user_spec.rb
spec/models/saved_page_spec.rb
spec/requests/attributes/names_spec.rb
spec/requests/attributes_spec.rb
spec/requests/user_spec.rb
spec/service_consumers/pact_helper.rb
spec/support/helpers/oidc_client_helper.rb

DB constraints are needed, because application code isn't infallible,
but Rails validations give nicer error messages than just a generic
"postgres constraint failed" exception, and mean that methods like
`valid?` will work.
I also moved the two path validators into their own named classes, to
make it clearer what the difference between the two is.
---
[Trello card](https://trello.com/c/J7Aba0jq/850-review-database-constraints-and-make-sure-we-have-rails-validations)

Add missing ActiveRecord validations & specs from DB constraints

---

app/controllers/email_subscriptions_controller.rb
app/controllers/oidc_users_controller.rb
app/models/email_subscription.rb
app/models/oidc_user.rb
config/routes.rb
db/migrate/20210611093439_create_email_subscriptions.rb
db/schema.rb
docs/api.md
spec/factories/email_subscription_factory.rb
spec/models/email_subscription_spec.rb
spec/requests/email_subscriptions_spec.rb
spec/requests/oidc_users_spec.rb
spec/service_consumers/pact_helper.rb

This PR adds an API for email subscription management, and makes it so that when the Identity Provider tells us that a user has a new email address, we update the subscriptions.
**Why not just use email-alert-api?**
Updating the subscriptions when the account updates needs a change in account-api, but couldn't we just use email-alert-api for the rest of this?  Why do we need an `email_subscriptions` table?  Well, there are two reasons:
1. Since consuming apps work with "names" rather than email topic slugs, they don't need to implement logic like:
1. Call email-alert-api with the old topic slug and the current email address to cancel the old subscription (this would be a new endpoint in email-alert-api)
2. Call email-alert-api with the new topic slug and current email address to create …

Implement email subscriptions

---

app/controllers/oidc_users_controller.rb
app/controllers/user_controller.rb
config/user_attributes.yml
spec/requests/oidc_users_spec.rb
spec/requests/user_spec.rb
spec/service_consumers/pact_helper.rb

This is not just `!email_verified`:
- `email` - this is the email address the user registered with, or a
new email address they have confirmed.
- `email_verified` - the user needs to verify the email address they
registered with, this starts `false`, becomes `true`, and then never
returns to `false`
- `has_unconfirmed_email` - this is `true` if `email_verified` is
`false` OR the user has a pending email change to confirm
So,
if has_unconfirmed_email
if email_verified
show "finish changing your email address" banner
else
show "confirm your account" banner
end
end
And set the attribute through `PATCH /api/oidc-users/:sub`.
We want to have the as many of the attributes needed to return the
`GET /api/user` response stored locally as possible, so the homepage
is nice and fast.
---
[Trello …

Add `has_unconfirmed_email` attribute, to be used in the account home page

---

app/controllers/user_controller.rb
docs/api.md
spec/requests/user_spec.rb

We'll need this in email-alert-api so we can record which GOV.UK
Account a Subscriber belongs to.  I thought about adding this to the
`GET /api/attributes` endpoint, but it feels like more of a user
concern to me.
We might want to retire the attributes endpoints at some point anyway
and consolidate stuff under `/api/user`.
---
[Trello card](https://trello.com/c/Vzd8so2T/874-implement-designs-for-managing-your-email-notifications-via-the-account)

Return the user ID in the `GET /api/user` response

---

app/controllers/user_controller.rb
spec/requests/user_spec.rb

This is a small future-proofing change: user IDs are integers now, but
we don't want consuming apps to treat them as such (eg, we might start
propagating subject identifiers at some point, and so they'll turn
into strings).  So let's return it as a string from the get-go.

Return user ID as a string

---

app/controllers/oidc_users_controller.rb
spec/requests/oidc_users_spec.rb

Currently, if a user updates their email address, any subscriptions
which account-api knows about will also be updated.  But any other
subscriptions for the same email address won't.  This isn't great.
To address this problem, we've added a concept of "linking" a
subscriber to a GOV.UK Account in email-alert-api.
So now the logic for updating email subscriptions is:
- Check if there is a linked subscriber:
- If so, update the address for that subscriber
- If not, update each subscription we know about
We're going to make some frontend changes to nudge people towards
linking their accounts.
---
[Trello card](https://trello.com/c/Vzd8so2T/874-implement-designs-for-managing-your-email-notifications-via-the-account)

Update linked subscribers on email address change

---

app/controllers/email_subscriptions_controller.rb
app/controllers/transition_checker_email_subscription_controller.rb
app/lib/account_session.rb
app/lib/oidc_client.rb
config/routes.rb
spec/lib/account_session_spec.rb
spec/requests/email_subscriptions_spec.rb
spec/requests/transition_checker_email_subscription_spec.rb
spec/service_consumers/pact_helper.rb

This PR handles `/api/email-subscriptions/transition-checker-results` as a special case, delegating to the account-manager rather than using the local database like other email subscriptions.
This is because, once the transition checker is no longer a special case, it will use these endpoints.  So we want to update finder-frontend to use them, and delete the old endpoints.
Then, when we have removed the JWT journey from finder-frontend (which we can do as soon as we have the new design for the post-registration confirmation page), we can update these special-cased endpoints to start migrating the subscription data out of account-manager.

Prepare to move transition checker subscriptions to the normal email endpoints

---

app/controllers/authentication_controller.rb
docs/api.md
spec/requests/authentication_spec.rb
spec/service_consumers/pact_helper.rb

We've not actually been doing this since migrating from the
finder-frontend session handling.

Return cookie consent from auth callback endpoint

---

app/controllers/authentication_controller.rb
app/lib/oidc_client.rb
app/models/auth_request.rb
config/routes.rb
docs/api.md
spec/lib/oidc_client_spec.rb
spec/requests/authentication_spec.rb
spec/service_consumers/pact_helper.rb

This has been removed from gds-api-adapters and is now unused.
See also https://github.com/alphagov/gds-api-adapters/pull/1092
---
[Trello card](https://trello.com/c/aEbuS4Tf/884-remove-the-jwt-sign-up-flow)

Remove `POST /api/oauth2/state` endpoint

---

app/controllers/email_subscriptions_controller.rb
spec/requests/email_subscriptions_spec.rb

All Transition Checker email subscription interactions are now going
through this controller, and the JWT method of creating subscriptions
is gone.
So now we can begin to migrate the state into account-api.
---
[Trello card](https://trello.com/c/5rNWhML7/885-begin-incremental-migration-of-transition-checker-email-subscriptions-from-account-manager-to-account-api)

Incrementally migrate Transition Checker subscriptions

---

app/lib/account_session.rb
spec/lib/account_session_spec.rb
spec/requests/attributes/names_spec.rb
spec/requests/attributes_spec.rb
spec/requests/email_subscriptions_spec.rb
spec/requests/user_spec.rb
spec/service_consumers/pact_helper.rb
spec/support/helpers/oidc_client_helper.rb

The userinfo response MUST have at least one attribute, "sub", the
user's "subject identifier", and MAY also have additional attributes.
In contrast, the `get_attribute` endpoint in our attribute-service
prototype only returns one attribute at a time.  So an account-api
request which needs to fetch multiple attributes (like `GET /api/user`)
will make multiple requests, in sequence, to fetch them.
Which is slow.
If we can get even one attribute from the userinfo response (and in
practice we can currently get *all* of them from the userinfo
response), then this change is worthwhile.
---
[Trello card](https://trello.com/c/RYLdsABd/906-fetch-remote-attributes-from-userinfo-if-present-there)

Fetch remote attributes from userinfo, if present there

---

app/lib/migrations/transition_checker.rb
lib/tasks/migrations.rake
spec/lib/migrations/transition_checker_spec.rb

After being run once we can delete this task and the account-manager
endpoint.
See also https://github.com/alphagov/govuk-account-manager-prototype/pull/893
---
[Trello card](https://trello.com/c/4ulBaTFk/887-bulk-migrate-older-transition-checker-state-from-account-manager-to-account-api)

Add rake task to migrate Transition Checker data

---

app/controllers/oidc_users_controller.rb
app/controllers/user_controller.rb
spec/requests/user_spec.rb

A JSON response gets parsed to a hash with string keys, not symbols.
So if we use symbols for attribute names, they don't match the
userinfo hash.
I considered making the userinfo a HashWithIndifferentAccess, but that
would encourage mixing strings and symbols for attribute names
throughout the code, which could be confusing.  So instead, use
strings for attribute names everywhere.
This change will make the optimisation in 26c945a apply to the
/account/home page.
---
[Trello card](https://trello.com/c/RYLdsABd/906-fetch-remote-attributes-from-userinfo-if-present-there)

Use strings for attribute names everywhere

---

Gemfile
Gemfile.lock
lib/tasks/migrations.rake

`httparty` wasn't in the Gemfile (but it was in the Gemfile.lock) but,
confusingly, it worked in the tests despite `bundle exec rake` giving
an uninitialized constant error when I tried to run it in staging.
Also add the missing `args` parameter to the task.
---
[Trello card](https://trello.com/c/4ulBaTFk/887-bulk-migrate-older-transition-checker-state-from-account-manager-to-account-api)

Fix migrations:transition_checker task

---

config/user_attributes.yml
spec/requests/user_spec.rb

We have now migrated this attribute fully into the account-api.
---
[Trello card](https://trello.com/c/4ulBaTFk/887-bulk-migrate-older-transition-checker-state-from-account-manager-to-account-api)

Mark transition_checker_state attribute as local

---

Gemfile
Gemfile.lock
Procfile
app/controllers/authentication_controller.rb
app/jobs/application_job.rb
app/workers/application_worker.rb
app/workers/expired_auth_request_worker.rb
config/application.rb
config/routes.rb
config/sidekiq.yml
spec/requests/authentication_spec.rb
spec/workers/expired_auth_request_worker_spec.rb

The app is doing a lot of garbage collection, and specifically it
looks like it's allocating a lot of ActiveRecord transaction objects.
I suspect that that's caused by this in the `sign_in` controller:
AuthRequest.expired.delete_all
Deleting expired objects on every request was implemented as an easy
"is this really worth setting up sidekiq for?" approach but, if it's
causing excessive allocation, and so excessive garbage collection,
it *is* worth setting up sidekiq to handle.
ActiveJob was already present in the app but I've removed it
completely (rather than configure it to use sidekiq as a queuing
system) because on GOV.UK we're more experienced with using sidekiq
directly.
See also https://github.com/alphagov/govuk-puppet/pull/11200
---
[Trello …

Move the deletion of expired AuthRequests to a sidekiq worker

---

Gemfile
Gemfile.lock

In 3.1.0 it tries to use `exists?` instead of `exists`, but `exists?`
does not exist:
https://github.com/moove-it/sidekiq-scheduler/issues/345
---
[Trello card](https://trello.com/c/uRW8OS61/907-move-expired-authrequest-deletion-to-sidekiq)

Downgrade to sidekiq-scheduler 3.0.1

---

app/models/oidc_user.rb

Since this method is constructing a hash, we can do that directly via
`each_with_object`.

Remove allocation of some intermediate lists

---

app/lib/user_attributes.rb
app/models/attribute_definition.rb
spec/lib/user_attributes_spec.rb
spec/models/attribute_definition_spec.rb

In the UserAttributes class there's a bunch of validation logic to
make sure that the config file is correct, and then in the specs
there's a bunch of test logic to make sure that the validation logic
works, and THEN we get to the real spec: a short one which validates
the config file.
There's already a way to define validations and test them:
ActiveRecord and shoulda-matchers.  And this sort of code is much more
familiar, so it's easier to read at a glance.
So, switch to using an OpenStruct including ActiveRecord::Validations
for attribute definitions, write some (short!) specs around the
validations, just to make sure nobody in the future accidentally
removes one, and then remove all the hand-written validation logic
from UserAttributes.

Move attribute definitions to OpenStruct / ActiveRecord

---

docs/api.md

On a semi-related note, I wonder about changing our API docs to look more like [the GitHub ones](https://docs.github.com/en/rest/reference/actions), which I think are easier to read.

Fix docs for `/api/oidc-users/:subject_identifier` endpoint

---

app/controllers/email_subscriptions_controller.rb
app/models/email_subscription.rb

This puts all of the email-alert-api communication in one place.  I've also moved an `update!` into an `ensure` block, to make it clearer that we always want it to run, and removed some superfluous `to_hash`es.

Move email subscription cancel checking logic into the model 

---

spec/service_consumers/pact_helper.rb

Pact tests in GDS API adaptors are [curretly][1] failing because there
is no is no provider_state in account-api with the expected name
`the-subject-identifier`.
This sets up a provider that will build a user record with that value
for the Pact to verify with.
[1]: https://github.com/alphagov/gds-api-adapters/pull/1098

Add new pact provider to build an oidc-user sub

---

bin/rails

This is causing problems with govuk-docker and conflicting dependency
versions:
Traceback (most recent call last):
15: from bin/rails:9:in `<main>'
14: from bin/rails:9:in `require_relative'
13: from /govuk/account-api/config/boot.rb:3:in `<top (required)>'
12: from /root/.rbenv/versions/2.7.2/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:155:in `require'
11: from /root/.rbenv/versions/2.7.2/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:155:in `require'
10: from /root/.rbenv/versions/2.7.2/lib/ruby/2.7.0/bundler/setup.rb:10:in `<top (required)>'
9: from /root/.rbenv/versions/2.7.2/lib/ruby/2.7.0/bundler/ui/shell.rb:88:in `silence'
8: from /root/.rbenv/versions/2.7.2/lib/ruby/2.7.0/bundler/ui/shell.rb:136:in `with_level'
7: from …

Remove simplecov from bin/rails

---

Gemfile
Gemfile.lock
app/workers/send_email_worker.rb
config/initializers/sidekiq.rb
config/secrets.yml
spec/workers/send_email_worker_spec.rb

We will use this to send special account-related emails to people;
this functionality won't be directly exposed in an API which other
apps can call to send one-off emails.
We're doing this in account-api rather than email-alert-api because
email-alert-api doesn't do emails to individual addresses: it does
emails to *lists*.  We could emulate this by creating a
single-subscriber list, sending the email, and then deleting the list;
but that's a bit of an abuse, we shouldn't go down that route.
I've gone for an approach similar to email-alert-api[1]: a Sidekiq job
which calls the Notify API directly.
I also looked at the mail-notify gem[2], but it looks like that
doesn't send email asynchronously, so we'd need to wrap calls to it in
a Sidekiq job anyway.
Finally, I considered using …

Set up email delivery with Notify

---

app/models/email_subscription.rb
config/locales/emails.en.yml
db/migrate/20210730125116_add_has_received_transition_checker_onboarding_email_to_oidc_user.rb
db/schema.rb
spec/models/email_subscription_spec.rb
spec/spec_helper.rb

When a user first signs up to Transition Checker notifications, we
want to send them an onboarding email.
This is part of the unbodging: the Account Manager is now sending a
much more generic email and so, on the GOV.UK side, we want to send
the more specific one.
This email will also be sent if the user signs up and only later uses
the Checker, whereas before they'd just have got the one
Checker-mentioning email regardless of whether they'd used the Checker
or not.
I thought about implementing the logic with some sort of check based
on attribute values, but decided it would be clearer (and less
fragile) to add a `has_received_transition_checker_onboarding_email`
field to the `OidcUser` model.  This new field defaults to `true`, so
we won't start sending any emails yet.  This lets us …

Implement Transition Checker onboarding email

---

config/locales/emails.en.yml

This logic hasn't been switched on yet, so nobody has received the incorrect email.
---
[Trello card](https://trello.com/c/aqRJqOKQ/914-send-brexit-checker-specific-welcome-email-when-someone-first-confirms-their-address)

Fix typo in Transition Checker Onboarding Email

---

db/migrate/20210730133729_change_default_for_has_received_transition_checker_onboarding_email.rb
db/schema.rb

This changes the `has_received_...` column default from true to false,
so users created after this point will be sent the email when they
first activate a Transition Checker subscription.
---
[Trello card](https://trello.com/c/aqRJqOKQ/914-send-brexit-checker-specific-welcome-email-when-someone-first-confirms-their-address)

Send Transition Checker onboarding email

---

app/controllers/email_subscriptions_controller.rb
app/controllers/oidc_users_controller.rb
app/models/email_subscription.rb
spec/models/email_subscription_spec.rb

The `reactivate_if_confirmed!` method needs the `email` and
`email_verified` attributes, which are cached attributes: they may not
be stored locally but, given a user session, we know how to retrieve
them.
So this method used to take the attributes as parameters.
However, this gives a slightly weird API where, strictly speaking,
subscriptions can be associated with a user which use a different
email address, or which are confirmed when the user is not (or vice
versa).  So, to rule out that possibility, treat the attributes as
local attributes in `reactivate_if_confirmed!`, and we just have to
make sure that they are present before calling it.

Fetch email & email_verified from OidcUser in EmailSubscription

---

app/lib/account_session.rb
spec/lib/account_session_spec.rb

We're implementing flash messages by appending keys to the session,
separated from the actual session with a "$$".  So, change the
`AccountSession` to drop any flash portion, as we don't need it in
this app.
---
[Trello card](https://trello.com/c/I0ulYzeX/946-implement-a-way-to-use-flash-messages-for-accounty-things)

Drop flash messages in the session

---

app/models/oidc_user.rb
db/migrate/20210715153551_add_local_attribute_fields_to_oidc_user.rb
db/schema.rb
spec/fixtures/user_attributes.yml
spec/lib/account_session_spec.rb
spec/requests/attributes/names_spec.rb
spec/requests/attributes_spec.rb
spec/requests/oidc_users_spec.rb

Having a separate table with named attributes works well when we don't
know what attributes we're going to have, as in principle it means a
client can all our API with any attribute names and we'd store or
return them appropriately.  But then we undermined that by defining
them all in a config file anyway.
Given that we're not really making use of the flexibility of the
current model, why not go all the way and merge it into a single
database table?  This will reduce database queries and lessen memory
allocation.
This commit will gradually migrate attributes into the `OidcUser`
model as they get updated.  We can do this in a big-bang style by
running this in a rails console:
OidcUser.find_each(&:set_local_attributes)
Then, when all the `LocalAttribute`s are gone, we can:
1. Deploy a PR …

Merge the `LocalAttribute`s into the `OidcUser` model

---

Gemfile
Gemfile.lock

We're explicitly using version 3.0.1, because 3.1.0 has an issue (mentioned in a comment above the version constraint):
```
ERR unknown command `exists?`, with args beginning with: `account-api:schedules`,
/data/vhost/account-api/shared/bundle/ruby/2.7.0/gems/redis-4.1.4/lib/redis/client.rb:126:in `call'
/data/vhost/account-api/shared/bundle/ruby/2.7.0/gems/redis-4.1.4/lib/redis.rb:3312:in `block in method_missing'
/data/vhost/account-api/shared/bundle/ruby/2.7.0/gems/redis-4.1.4/lib/redis.rb:51:in `block in synchronize'
/usr/lib/rbenv/versions/2.7.2/lib/ruby/2.7.0/monitor.rb:202:in `synchronize'
/usr/lib/rbenv/versions/2.7.2/lib/ruby/2.7.0/monitor.rb:202:in `mon_synchronize'
/data/vhost/account-api/shared/bundle/ruby/2.7.0/gems/redis-4.1.4/lib/redis.rb:51:in `synchronize' …
```

Revert "Bump sidekiq-scheduler from 3.0.1 to 3.1.0"

---

app/controllers/authentication_controller.rb
app/controllers/concerns/authenticated_api_concern.rb
app/lib/account_session.rb
app/lib/string_encryptor.rb
config/secrets.yml
spec/lib/account_session_spec.rb
spec/lib/string_encryptor_spec.rb
spec/support/helpers/govuk_account_session_helper.rb

It's not the key, it's the secret used to derive the key.
When the env var has been renamed in puppet, the old one can be
removed from config/secrets.yml.

Rename session_signing_key to session_secret

---

app/controllers/concerns/authenticated_api_concern.rb

Previously, we supported taking the account session value from the
request cookies when running in development mode.  This matches how
the frontend apps behave.  But in practice we don't make requests
directly to account-api itself from a browser, so this is unnecessary.

Remove unused development-mode branch

---

app/controllers/authentication_controller.rb
app/lib/account_session.rb
app/lib/oidc_client.rb
config/routes.rb
docs/api.md
spec/lib/account_session_spec.rb
spec/requests/authentication_spec.rb
spec/support/helpers/govuk_account_session_helper.rb
spec/support/helpers/oidc_client_helper.rb

This commit adds the original ID token value (a JWT) to the session, so that we can follow the [OIDC session management standard](https://openid.net/specs/openid-connect-session-1_0.html) Digital Identity have adopted.  The account manager doesn't use this standard (it has its own way of logging users out), so this is another bit of code with an `if using_digital_identity?` case - which isn't great, but is only temporary.
We'll need to add this endpoint to gds-api-adapters, then it can be used in the current [frontend SessionsController](https://github.com/alphagov/frontend/blob/5d7f08f7ad87033f3d602d378609aa6e74d720a0/app/controllers/sessions_controller.rb#L29-L38).
---
[Trello card](https://trello.com/c/ZvDGaba4/958-use-di-auth-in-integration-give-feedback-on-their-documentation)

Store the ID token JWT in the session, and add an end-session endpoint

---

lib/message_queue_processor.rb
spec/lib/message_queue_processor_spec.rb

Currently if a redirect target is `gone`, this throws an exception:
```
GdsApi::HTTPGone: URL: https://content-store.production.govuk-internal.digital/content/international-development-funding/rapid-funding-envelope-for-hiv-aids-tanzania
Response body:
{"analytics_identifier":null,"base_path":"/international-development-funding/rapid-funding-envelope-for-hiv-aids-tanzania","content_id":null,"document_type":"gone","first_published_at":null,"locale":"en","phase":"live","public_updated_at":"2016-08-09T13:29:27.000+00:00","publishing_app":"specialist-publisher","publishing_scheduled_at":null,"rendering_app":null,"scheduled_publishing_delay_seconds":null,"schema_name":"gone","title":null,"updated_at":"2021-06-09T10:10:15.309Z","withdrawn_notice":{},"publishing_request_id":null,"links":{},"descr …
```

Handle content-store gone exceptions when redirecting saved pages

---

app/controllers/authentication_controller.rb

I think this is making us hit an HTTP header size limit.  The HTTP
spec doesn't define such a limit, but servers commonly have one:
nginx (which we use) is 4KB to 8KB.
With the ID token included, the full session value when I log in on
staging is 2704 bytes.  2KB is a big chunk of a 4KB to 8KB limit.
There are no app errors logged to Sentry, and I can see the
account-api is returning a 200 response to frontend, so the apps
themselves seem to be working - but a 503 error is returned to the
browser.
This doesn't seem to happen on integration.  Maybe DI have smaller ID
tokens than we do?  In any case, the problem on staging isn't
promising, and suggests that even though things are working on
integration we're likely close to a limit.
So I think we'll need to store ID tokens server side. …

Do not store ID token JWT in the session

---

app/controllers/authentication_controller.rb
spec/requests/authentication_spec.rb
spec/support/helpers/oidc_client_helper.rb

Using `fetch` implies that the value is present, but that's not
necessarily the case:
- Digital Identity don't yet have refresh tokens
- They're going for a different approach for GA session IDs
- A missing cookie consent value is treated as false
So rather than fill in `nil` or `false` as default values for these
things, just allow them to be missing.
---
[Sentry error](https://sentry.io/organizations/govuk/issues/2623524890/?project=5671868&referrer=slack)

Do not use `fetch` for values which can safely be `nil`

---

app/controllers/oidc_users_controller.rb
app/lib/account_session.rb
app/models/oidc_user.rb
spec/models/oidc_user_spec.rb
spec/service_consumers/pact_helper.rb

The `find_or_create_by!` method isn't atomic, it's implemented like
so:
def self.find_or_create_by!(options)
find_by(options) || create!(options)
end
So if two threads do a `find_or_create_by!` concurrently, there's a
race condition.  For `OidcUser`s, we can't end up with duplicate
records, as we always do `find_or_create_by!(sub: ...)`, and there's a
unique index on `sub`.  Instead we just get a `RecordNotUnique` error,
which isn't great.
We've only seen this issue crop up once, so it's pretty rare.  But
it'll likely become more common as we get more active users.  So,
handle the case where the record isn't unique by doing a `find_by!`.
Unfortunately, there isn't a good way to test that the race condition
is fixed.  But, since the error is ultimately coming from the
database (as it's a …

Make find_or_create OidcUser atomic

---

app/lib/account_session.rb
spec/lib/account_session_spec.rb

DI don't have this attribute, so we never cache a value for it, which
means every page which uses it makes a userinfo request.
That's bad because it adds latency (there's an extra network request
going on) and it imposes a session timeout due to the OAuth access
token expiring (if a user tries to use an invalid token we force them
to reauthenticate).
Since DI do not have users with unconfirmed email addresses, as a
hacky work-around we can hard-code this to false.  When we've migrated
to DI in production *and* removed use of this attribute, we can remove
this special case.
---
[Trello card](https://trello.com/c/ZvDGaba4/958-use-di-auth-in-integration-give-feedback-on-their-documentation)

Special-case `has_unconfirmed_email` attribute when using DI

---

spec/requests/oidc_users_spec.rb

This test very rarely fails with an off-by-one in the user ID
stubbed (eg, the request is for user 1 but the stub is for user 2).  I
assume there's some race condition between one test being cleaned up
and the next test being run.
Reading the postgres counter directly is a bit of a smell though so,
since in these tests we don't care so much about the exact user ID,
just use a regex URL pattern for the stub.
---
Here's an example test failure: https://ci.integration.publishing.service.gov.uk/job/account-api/job/main/187/console

Fix flaky test

---

Gemfile
lib/tasks/support.rake
spec/lib/support_spec.rb

Look up users by email address to see if they have an account. We have
to do this occasionally, so add a more convenient method than using the
Rails console.
[Trello card](https://trello.com/c/MoyeH1GU/1017-add-a-rake-task-to-check-if-an-account-exists)

Add a rake task to check if a user exists

---

db/migrate/20210920101003_remove_local_attributes.rb
db/schema.rb

The use of this was removed in #185.  This migration is, strictly
speaking, reversible: the data which was in this table was migrated
into the `oidc_users` table by #149.  So we could revert this and
deploy code to pull the data back out if need be.

Drop `local_attributes` table

---

app/controllers/authentication_controller.rb
app/controllers/user_controller.rb
app/lib/account_session.rb
docs/api.md
spec/lib/account_session_spec.rb
spec/requests/attributes_spec.rb
spec/requests/user_spec.rb
spec/service_consumers/pact_helper.rb
spec/support/helpers/govuk_account_session_helper.rb

Also, since we're no longer exposing this in the public API, we don't need to store it in the session any more, and can just store an MFA flag.
---
[Trello card](https://trello.com/c/ZvDGaba4/958-use-di-auth-in-integration-give-feedback-on-their-documentation)

Remove level of authentication from public API

---

app/controllers/authentication_controller.rb
spec/requests/authentication_spec.rb

This parameter is passed as a GET parameter, not a JSON POST
parameter, so it's decoded to the string `"false"` (which is truthy)
rather than the value `false`.

Fix interpreting ?mfa=false as truthy & add test

---

app/models/oidc_user.rb
db/migrate/20210930103307_add_legacy_sub_to_oidc_user.rb
db/schema.rb
spec/models/oidc_user_spec.rb

This commit adds the column and starts saving values for new users.
There will be a follow-up migration to copy over values for existing
users, make the column non-null, and add a unique index.
To handle the change in subject identifiers when we switch to DI,
we'll look up users like so:
```ruby
def self.find_or_create_by_sub!(sub:, legacy_sub:)
transaction do
user = OidcUser.find_by(sub: sub)
return user if user
user = OidcUser.find_by(legacy_sub: legacy_sub)
if user
user.update!(sub: sub)
return user
end
OidcUser.create!(sub: sub, legacy_sub: legacy_sub)
end
end
```
Pre-DI migration, `sub` and `legacy_sub` will always be the same.
Post-DI migration, the only ambiguous case is when decoding a session:
is the sub in the session old or new?  We'll solve that with the card
to add a version …

Add `legacy_sub` field to `OidcUser`

---

app/controllers/oidc_users_controller.rb

If a user signs up and then confirms their email address before
returning to GOV.UK, this endpoint will create the user record.
Pre-migration, we need to record the sub as the `legacy_sub` in this
case.
---
[Trello card](https://trello.com/c/eRBL2kEZ/1050-implement-migration-of-subject-identifiers)

Set `legacy_sub` when creating a user to update

---

app/controllers/check_email_subscription_controller.rb
config/content_items.yml
config/routes.rb
docs/api.md
spec/requests/check_email_subscription_spec.rb

[Trello](https://trello.com/c/4kqU5mjD/1051-add-public-endpoint-to-account-api-to-check-if-the-current-user-has-a-subscription)
Add a personalisation endpoint in prepartion of our progressive enhancement features, it will allow a logged in user to gain a minimal amount of information about email subscriptions so that we can vary front ends.
Have separated the commits for ease of review, will squash down to a single commit when it comes out of draft.

Personalisation route

---

app/lib/oidc_client/fake.rb
spec/lib/oidc_client/fake_spec.rb

The method has to return a result in the form:
{
access_token: access_token,
result: { actual userinfo response },
}
To match the real client.  Otherwise the authentication controller
callback throws an error calling `merge!` on nil.

Fix format of fake userinfo response when running locally

---

app/controllers/concerns/authenticated_api_concern.rb
app/controllers/match_user_by_email_controller.rb
config/routes.rb
db/migrate/20211101130206_add_index_on_oidc_users_email.rb
db/schema.rb
docs/api.md
spec/requests/match_user_by_email_spec.rb
spec/service_consumers/pact_helper.rb

This will be used to implement the sniffer page in
email-alert-frontend, where we want to examine the email address the
user has just entered and do one of three things:
- Log the user in to email-alert-frontend if they're logged into the
right GOV.UK account; or
- Tell the user to sign in, if a GOV.UK account exists with the email
address they entered; or
- Fall back to the magic link method if there is no GOV.UK account for
that email address.
email-alert-frontend will use this endpoint like so:
def match_user_by_email(email)
response = GdsApi.match_user_by_email(
email: @address,
govuk_account_session: account_session_header,
)
if response["match"]
:ok
else
:must_reauthenticate
end
rescue GdsApi::HTTPNotFound
:no_account
end
The alternative would be to add an endpoint to find a user by …

Add endpoint to match a user by email address & add an index on the field

---

app/models/unmigrated_oidc_user.rb
db/migrate/20211103101514_move_unmigrated_users_to_new_table.rb
db/schema.rb
lib/tasks/migration.rake

There are ~7000 users who didn't confirm their email address before
the cut-off date, and so who didn't get migrated.  9 of those have
since re-registered, which means we have 9 `OidcUser` records with
duplicate email addresses.
This causes a problem, because email addresses are otherwise unique.
So, let's move these users to another table.  Eventually we will
delete them, but that won't happen until after the brexit checker goes
away at least.
---
[Trello card](https://trello.com/c/eIgHkyyw/1123-move-unmigrated-users-to-a-different-database-table)

Add rake task to move unmigrated users to a new table

---

app/models/oidc_user.rb
spec/models/oidc_user_spec.rb

This prevents destroying unmigrated users, as their sub and legacy_sub
are the same.  For migrated users, we don't need to know the destroyed
legacy_sub, because if we try to join up data with DI, we'll do it by
the sub instead.

Do not create tombstone records for legacy subs

---

app/controllers/concerns/authenticated_api_concern.rb
app/controllers/match_user_by_email_controller.rb
config/routes.rb
db/migrate/20211101130206_add_index_on_oidc_users_email.rb
db/schema.rb
docs/api.md
spec/requests/match_user_by_email_spec.rb
spec/service_consumers/pact_helper.rb

Reverts #263
The unmigrated users have been moved to a separate table, and there
are no longer any duplicate email addresses in the main oidc_users
table.
---
[Trello card](https://trello.com/c/5ZoujfPL/1115-implement-email-management-account-sniffer-logic)

Revert "Revert "Add endpoint to match a user by email address & add an index on the field""

---

app/controllers/application_controller.rb
app/controllers/authentication_controller.rb
app/controllers/oidc_users_controller.rb
app/models/sensitive_exception.rb
db/migrate/20211104103629_create_sensitive_exceptions.rb
db/schema.rb
spec/requests/oidc_users_spec.rb

These exceptions can be raised due to non-unique email addresses.
Such an exception indicates a bug, as email addresses should be
unique, but we don't want real user data getting into Sentry.

Store exceptions from updating users to a new table

---

config/sidekiq.yml

We only use sidekiq currently to delete old `AuthRequest`s, we don't
need the default of 10 workers.  By reducing this, we'll reduce the
memory usage on the machine, and let us increase the number of unicorn
workers.

Reduce sidekiq concurrency to 2

---

lib/tasks/support.rake

I've just been doing this in a Rails console, but every time I have to
look up what the Rack function is called; and in any case it's better
to not need regular production console access.

Add a rake task to return a user's transition checker results

---

lib/tasks/migration.rake

This is to handle the case where a legacy_subject_id isn't being
returned from the userinfo, and so we're trying to create a new
OidcUser record with the same email address as an existing,
pre-migration, one.
We have one such case so far (brought to light by the new unique index
on the email field).  I've asked DI to check the record for that user,
as they should have been migrated across.  But, so that the user can
log in, we need to merge their two records.
The task will only merge users where:
- the post-migration user has no legacy_sub or email.
- the pre-migration user has the same sub and legacy_sub.
- both users were created on the right sides of the migration.
---
[Trello card](https://trello.com/c/GYLhX263/1125-investigate-improperly-migrated-user)

Add rake task to merge pre- & post-migration users

---

app/controllers/check_email_subscription_controller.rb
docs/api.md
spec/requests/check_email_subscription_spec.rb

If a base_path is given, we match against the URL field of the
subscriber list.  This is so we can find a subscription for a specific
page, without needing the frontend app to query email-alert-api for
the slug first.
I've also added tests for the case where a user has active
subscriptions which don't match, as that wasn't covered previously.
---
[Trello card](https://trello.com/c/oOpGMmxF/1126-put-the-single-page-signup-button-on-some-pages)

Make check-email-subscription endpoint also take a base_path

---

config/content_items.yml
lib/publishing_api_tasks.rb
lib/tasks/publishing_api.rake
spec/lib/publishing_api_tasks_spec.rb

We've decided that, since all the account things are under `/account`, the actual top-level path `https://www.gov.uk/account` should do something too.
Also refactor the PublishingApiTasks a bit:
- Specify the locale for help pages and redirects (to be consistent with special routes)
- Add a helper method to do the put-content & publish step
- Add some test helper methods to reduce repetition
---
[Trello card](https://trello.com/c/OIJrfei8/1128-make-account-redirect-to-account-home)

Publish a redirect from /account to /account/home

---

app/controllers/check_email_subscription_controller.rb
config/application.rb

This is needed for the govuk_personalisation controller concern in
development mode.  An alternative would be parsing the `Cookie`
request header ourselves.

Enable cookie middleware

---

app/controllers/check_email_subscription_controller.rb
docs/api.md
spec/requests/check_email_subscription_spec.rb

This is so that the javascript can just replace the existing button,
rather than trying to do some more fancy DOM manipulation.
---
To try this out locally, you'll also need #277 
---
[Trello card](https://trello.com/c/oOpGMmxF/1126-put-the-single-page-signup-button-on-some-pages)

Add single-page button HTML to the API response 

---

app/controllers/application_controller.rb
spec/requests/oidc_users_spec.rb

Throwing a `CapturedSensitiveException` inside a `rescue` embeds the
details of the causing exception inside it.  This is usually a useful
feature, letting you drill down into the root cause of a problem.
But when our goal is to hide exceptions which contain user data, it's
not so helpful.
This commit adds a handler for `CapturedSensitiveException`s which
just reports a string (and the ID of the newly-created
`SensitiveException` record) to Sentry.  Since we're not reporting an
actual exception object, there's no stack trace or any other details
being sent to Sentry.

Omit details of root cause when reporting a sensitive exception

---

app/controllers/oidc_users_controller.rb
spec/requests/oidc_users_spec.rb
spec/service_consumers/pact_helper.rb

When a user is deleted, we end the subscriptions we know about in
account-api: currently this is just the brexit checker subscription.
This commit extends that to handle ending *all* subscriptions, in the
case where the user has linked their notifications account to their
GOV.UK account.
---
[Trello card](https://trello.com/c/32TCYJFr/1152-end-a-users-email-subscriptions-when-they-delete-their-account)

For linked accounts, end notifications on account deletion

---

app/controllers/check_email_subscription_controller.rb
docs/api.md
spec/requests/check_email_subscription_spec.rb

It's possible to have two of these buttons on a page - one before and
one after the content. We'd like to be able to track clicks on these
separately in Google Analytics, so we need some way of differentiating
them.
Accept an optional  `button_location` parameter to the check email
subscriptions route and pass it on to the component so the component
can handle adding the required attributes for click tracking.
Also return the `button_location` in the JSON response to aid debugging.
[Trello](https://trello.com/c/oOpGMmxF/1126-put-the-single-page-signup-button-on-some-pages)

Pass location to email subscription button

---

lib/publishing_api_tasks.rb
lib/tasks/publishing_api.rake
spec/lib/publishing_api_tasks_spec.rb

We have a way of publishing them all, but not a single one.
Let's change that, you can pass in a contnet ID.
If that ID is not stored amongst this apps special routes, then return
early and output a message.

Add a rake task to publish a single special route

---

app/controllers/authentication_controller.rb
docs/api.md

This value has always been `nil` since we migrated to DI in
production.

Remove unneeded ga_client_id parameter from auth callback response

---

app/controllers/internal/authentication_controller.rb
app/controllers/internal/oidc_users_controller.rb
app/controllers/internal/user_controller.rb
app/lib/oidc_client/fake.rb
config/user_attributes.yml
db/migrate/20211207090018_remove_has_unconfirmed_email_from_oidc_users.rb
db/schema.rb
docs/api.md
spec/factories/oidc_user_factory.rb
spec/lib/oidc_client/fake_spec.rb
spec/requests/authentication_spec.rb
spec/requests/oidc_users_spec.rb
spec/requests/user_spec.rb
spec/service_consumers/pact_helper.rb

This attribute is no longer used since we
switched to DI's SSO service as they require users to confirm their
email address as part of the account creation journey.
[Trello](https://trello.com/c/SdkcF8EO/13-remove-hasunconfirmedemail-attribute)

Remove `has_unconfirmed_email` attribute

---

app/controllers/internal/oidc_users_controller.rb
docs/api.md
spec/requests/oidc_users_spec.rb

These parameters were only used to migrate data from the account
manager.

Remove cookie & feedback consent from OidcUsersController

---

app/controllers/application_controller.rb
app/controllers/internal/authentication_controller.rb
app/controllers/internal/oidc_users_controller.rb

`tags` is a way of filtering events.  When looking at a group of
events, you can click the "tags" panel, and then click a tag value to
filter to only those events with the same tag.
`extra` is a way of adding additional information to a single event.
When looking at a group of events, each has an "Additional Data"
section (beneath the "Operating System" and "Runtime" sections).  No
changing of panels needed, it's right there.
So change to `extra` here as it's more correct (and more convenient)
for what we're trying to do: attach unique data to each event.
---
```ruby
GovukError.notify("Michael's Test Error", { tags: { some_tag_here: "tag-value" } })
```
```ruby
GovukError.notify("Michael's Test Error", { extra: { extra_data_here: "extra-data-value" } })
```

Use `extra`, not `tags`, for captured sensitive exception IDs

---

app/views/help_pages/sign_in.html.erb

Update the list of services on `www.gov.uk/sign-in`:
- Add 'Report a COVID-19 rapid lateral flow test result'
- Move 'Passenger locator form' up a position & update the description
- Replace 'Manage your student loan balance' with 'Manage your GOV.UK emails'
After these changes are deployed to production we'll need to run the `publishing_api:publish_help_page[sign_in]` rake task to update the page. 
[Trello](https://trello.com/c/qLJfEnY4/1180-add-lateral-flow-test-and-email-updates-to-sign-in-to-a-service)
[Figma](https://www.figma.com/file/LjCm4D7zaur9zLXjJ0aylu/Sign-in-to-a-service-(sorting-hat)-experiment?node-id=865%3A3867)
The new page:
⚠️ This repo is Continuously Deployed: make sure you [follow the guidance](https://docs.publishing.service.gov.uk/manual/development-pipeline.html#mer …

Update content on `/sign-in`

---

app/controllers/internal/authentication_controller.rb
app/lib/oidc_client.rb
app/lib/oidc_client/fake.rb
spec/lib/oidc_client/fake_spec.rb
spec/lib/oidc_client_spec.rb
spec/requests/authentication_spec.rb
spec/support/helpers/oidc_client_helper.rb

Our pre-DI auth prototype service issued refresh tokens.  We used
these to fetch the UserInfo response when a user tried to use an
attribute which we don't have cached for them.
DI do not do refresh tokens, so we made the minimal change needed to
our code: we added support for there *not* being a refresh
token (rather than assuming one always exists) and also made the
attribute-caching happen as soon as the access token is fetched, not
when the attribute is needed.  But we left the ability to use refresh
tokens in place.
DI have spotted us using invalid access tokens on occasion, and have
suggested that we might be re-using tokens.  This is kind of weird as
we now only use the access token to fetch the userinfo in the auth
callback: there are two places where we do that, but we share the …

Remove use of refresh tokens entirely

---

README.md
app/controllers/internal/user_controller.rb
config/user_attributes.yml
docs/api.md
lib/tasks/support.rake
spec/lib/account_session_spec.rb
spec/requests/attributes_spec.rb
spec/requests/user_spec.rb
spec/service_consumers/pact_helper.rb

This commit removes all the code and tests referencing the
transition_checker_state attribute, and relevant examples from the
docs.
In a follow-up commit deployed after this one, we should add a
database migration to drop these from the database:
- `oidc_users.has_received_transition_checker_onboarding_email`
- `oidc_users.transition_checker_state`
- `unmigrated_oidc_users`
One downside of this change is that we no longer have an attribute
which stores arbitrary JSON, so the "correctly round-trips local
attributes" test is now much weaker: it's only testing that we handle
booleans properly.  I considered adding a test attribute, but that
felt like a step too far.
---
[Trello card](https://trello.com/c/cWrCi7H3/1231-remove-left-over-code-references-to-the-transition-checker)

Remove references to transition checker

---

db/migrate/20220125163309_remove_old_transition_checker_state.rb
db/schema.rb

This commit removes the transition checker state from the `oidc_users`
table, and drops the `unmigrated_oidc_users` table entirely.  This
migration is not reversible.
It's worth noting that we've not had any tickets which needed us to
check whether a user existed but wasn't migrated since the original
flurry of migration tickets.  So dropping the entire
`unmigrated_oidc_users` table, rather than just the column for saved
transition checker results, seems sensible.  If we do need this
information, we can always consult the backup we took of the
account-manager database before shutting that app down.
---
[Trello card](https://trello.com/c/cWrCi7H3/1231-remove-left-over-code-references-to-the-transition-checker)

Remove old transition checker state

---

docs/digital-identity.md

[Rendered](https://github.com/alphagov/account-api/blob/msw/digital-identity-docs/docs/digital-identity.md)
This covers all the likely DI problems I can think of for now.  This doc is intended to be helpful to any 2ndline devs who have to resolve a problem with accounts when no devs on the team are around, so it goes into some details which could be gleaned from the code.

Add some docs on the Digital Identity integration, and debugging it

---

Gemfile.lock

1.9.0 was yanked
CHANGELOG: https://github.com/ruby-i18n/i18n/releases

Update i18n to 1.9.1

---

app/lib/oidc_client.rb
spec/lib/oidc_client_spec.rb

This is a temporary measure to help diagnose an ongoing incident.
Capture errors when calling the `tokens` and `userinfo` endpoints to a
`SensitiveException` and cause a Sentry alert. Continue to raise an
`OAuthFailure` in these cases so the existing behaviour doesn't change.
---
[Trello](https://trello.com/c/GY5uRKms/1298-log-failed-requests-to-auth-oidc-tokens-and-userinfo-endpoints)

Capture OAuth failures

---

app/lib/oidc_client.rb
db/migrate/20220310145815_add_extra_information_to_sensitive_exception.rb
db/schema.rb

Whilst trying to debug we need more information about a subset of
errors. Here we add a next text string (intended for string encoded
JSON), and then supply it with a response code, response body and access
token info for a certain category of error.
We will want to remove this once we're done.

Add extra_info to sensitve exception

---

app/views/help_pages/sign_in.html.erb

Remove passenger locator form from the list of services on "Sign in to a
service".
This is because travel rules are changing from Friday 18th March and
this step in travel will no longer be necessary.
Do not release this change until Friday March 18th
-----
https://trello.com/c/JozVHrIL

Update content for Sign in to a service page

---

app/models/sensitive_exception.rb
app/workers/expired_sensitive_exception_worker.rb
config/sidekiq.yml
spec/workers/expired_sensitive_exception_worker_spec.rb

We use `SensitiveExceptions` to store error messages which may contain
personal data so we can report the error in Sentry or Kibana but only
store the data and error message in our database.
We're also planning to use this mechanism to capture error responses
from the Auth team's OIDC API. These may contain authorisation codes
and access tokens which would allow access to a user's account.
We need a mechanism which automatically deletes these database records
once they're no longer useful to us. We should be getting a Sentry alert
and investigation quickly once an exception is raised, so we don't
need to keep them around for very long.
`AuthRequest`s have a very similar mechanism for cleaning up old entries
so reusing that makes sense.
We chose 14 days as the retention period as this …

Add a worker to delete old `SensitiveExceptions`

---

app/lib/oidc_client.rb
spec/lib/oidc_client_spec.rb

This is a temporary measure to help debugging and has no effect on
successful logins.
Store the processed response from the tokens endpoint in an instance
variable. Then, if the following call to userinfo fails, include the
tokens response in the `SensitiveException` information. This will
allow us to ensure that the tokens match what we send to the OIDC
provider and also check the time between calls (as the access token has
a low TTL).
---
[Trello](https://trello.com/c/LmNPwBAb/1299-investigate-incident-p3-some-users-may-be-unable-to-sign-in-or-create-an-account)

Log tokens response for failed userinfo calls

---

app/views/help_pages/sign_in.html.erb

Remove reference to Verify from the content for the [sign in page](https://www.gov.uk/sign-in).
This is to go live tomorrow 1st April 2022. 
HMRC are withdrawing Verify from this date.
-----

Remove reference to GOVUK Verify

---

Gemfile
Gemfile.lock
app/lib/logout_token.rb
spec/lib/logout_token_spec.rb

[Trello](https://trello.com/c/p3328fd0/1346-create-a-new-endpoint-to-support-auth)
We're implimenting OIDC backchannel logout, to recieve messages from digital identity
indicating the uses wishes to have their session removed everywhere.
The initial stage of this is to:
- give `account-api` the awarenss of a LogoutToken
- Validate and verify contents [following the specification](https://openid.net/specs/openid-connect-backchannel-1_0.html#Validation)
- Ensure the JWT can be decoded correctly and the signature verified
This PR adds a Plain old ruby class to do just that.

Logout token

---

config/user_attributes.yml
db/migrate/20220520081234_add_local_attribute_to_oidc_user.rb
db/schema.rb
spec/lib/account_session_spec.rb
spec/requests/attributes_spec.rb
spec/service_consumers/pact_helper.rb

We are planning to remove the cookie and feedback consent attributes
as these are no longer going to be stored in the account API. However,
these are the last two local attributes and are used throughout the test
suites to test the logic for local attributes vs. cached attributes.
Removing them would therefore cause all the unit tests to fail. Rather
than deleting all the logic differentiating between attribute types at
this stage (which will take a while), we are adding a new local
attribute which is only used for testing.
We will then update the pact tests to use this new attribute, then
remove the cookie and feedback consent attributes and drop the data.
We'll then be in a place where we can clean up the tech debt introduced
by this commit and remove all the logic for local attributes. …

Add a `local_attribute` attribute for testing

---

spec/service_consumers/pact_helper.rb

The default branch of https://github.com/alphagov/gds-api-adapters has
changeed to `main`. This repo includes the consumer part of the pact
tests for this API, so update the test config to look at the correct
branch.

Change pact tests to use `main` branch

---

app/controllers/application_controller.rb
app/controllers/internal/authentication_controller.rb
app/controllers/internal/oidc_users_controller.rb
app/controllers/oidc_events_controller.rb
app/models/logout_notice.rb
app/models/oidc_user.rb
config/routes.rb
docs/api.md
spec/lib/oidc_client_spec.rb
spec/models/logout_notice_spec.rb
spec/models/oidc_user_spec.rb
spec/requests/back_channel_logout_spec.rb
spec/requests/logout_notice_invalidation_spec.rb
spec/support/helpers/oidc_client_helper.rb

[Jira - GUA-22](https://govukverify.atlassian.net/browse/GUA-22)
Add a Backchannel logout endpoint which:
- Recieves a request with a logout_token as an signed JWT.
- Responds with 400 if the JWT is invalid, or the signature cannot be validated
- Responds 200 and creates a LogoutNotice if the JWT is valid.
A logout Notice is a Redis persisted `sub`, it is intended to sit there and await a visit from a user attempting to authorise with that sub. Upon success it will trigger a logout and redirect.
This PR only impliments the backchannel logout endpoint and expiry notice creation. Two follow up PRs will shortly be needed:
1. To check authorised internal requests and queries to the personalisation endpoint with a valid session cookie log out a user and redirect. This will need to _not_ apply …

GUA-22 - Backchannel logout endpoint

---

app/models/tombstone.rb
app/workers/expired_tombstone_worker.rb
config/sidekiq.yml
spec/workers/expired_tombstone_worker_spec.rb

In [[1]] we allowed there to be multiple Tombstones with the same sub
as this app is no longer the canonical place for account creation and
deletion data.
Since we're no longer checking for duplicates, we can also start
deleting old records as they're now only really useful for debugging.
We went with 30 days as that matches the time needed for an account to
be marked 'inactive' by email alert API.
We do lose the ability to count the number of accounts that has ever
existed by adding this worker but, as mentioned before, this app isn't
the right place to count this anyway so it's not a real loss.
[1]: https://github.com/alphagov/account-api/pull/421
⚠️ This repo is Continuously Deployed: make sure you [follow the guidance](https://docs.publishing.service.gov.uk/manual/development-pipeline. …

Delete old Tombstone records

---

config/sidekiq.yml

`1hr` isn't a format Sidekiq recognises, so the worker processes were
crashing when started.

Fix `ExpiredTombstoneWorker` sidekiq schedule

---

app/lib/account_session.rb
app/lib/user_attributes.rb
app/models/attribute_definition.rb
config/user_attributes.yml
db/migrate/20220608082309_remove_local_attribute_from_oidc_users.rb
db/schema.rb
spec/lib/account_session_spec.rb
spec/models/attribute_definition_spec.rb
spec/requests/attributes_spec.rb
spec/requests/authentication_spec.rb
spec/requests/email_subscriptions_spec.rb
spec/service_consumers/pact_helper.rb

In #418 we removed the last two local attributes, cookie and feedback
consent. In that PR we replaced them with a dummy local attribute that
allowed all the logic to stay in place temporarily.
This PR cleans up after that one by removing attribute types and the
logic associated with what used to be `local` attributes. We only have
what used to be `cached` attributes left, which are those provided by
the IDP and aren't allowed to be updated by internal GOV.UK apps.
We might want to add other attributes in the future and we don't want
to break existing behaviour when trying to update these attributes
(which will return a 403), so this PR removes the logic for
updating attributes and the associated tests but leaves the `update`
controller method in place. This means the change to …

Remove attribute types and local attribute logic

---

app/views/help_pages/sign_in.html.erb

Update the content of the "Sign in to a service" page based on most recent analytics data. Tweak service description wording to match commonly used search terms.
Before and after of the content updates in the Figma file:
https://www.figma.com/file/LjCm4D7zaur9zLXjJ0aylu/Sign-in-to-a-service-(sorting-hat)-experiment?node-id=69%3A263 
-----

GUA-335: Update content for "Sign in to a service"

---

Gemfile.lock
app/lib/oidc_client.rb

Reverts alphagov/account-api#513
Likely cause of these errors: https://sentry.io/organizations/govuk/issues/3727423113/?project=5671868

Revert "Bump openid_connect from 1.4.0 to 2.2.0"

---

Gemfile.lock
app/lib/oidc_client.rb
spec/lib/oidc_client_spec.rb
spec/requests/authentication_spec.rb
spec/support/helpers/oidc_client_helper.rb

We need to update how we're getting back results - seems like faraday is returning pre-parsed bodies, so we're getting errors like this:
https://sentry.io/organizations/govuk/issues/3727423113/?referrer=slack
Openid connect changes that might be relevant:
https://github.com/nov/openid_connect/compare/v1.4.0...v2.2.0#diff-1e4b17b797d3704d8ba5d6eeed053f777bc25e5fac07e4a453e32aa4e8a72aacR29
Probable changes - check where bodies are being parsed that don't need to be, update test mocks to return pre-parsed data.
Reverts alphagov/account-api#532
https://trello.com/c/8eLTjlLQ/1644-dependahour-update-openidconnect-to-v2-in-account-api

Revert "Revert "Bump openid_connect from 1.4.0 to 2.2.0""

---

config/initializers/sidekiq.rb

This is no longer necessary as of Sidekiq 6.3.0, and indeed breaks sidekiq in updated versions.
Ref: https://github.com/mperham/sidekiq/commit/90535ab104b6540104af548d15baacd1291ffb5f (6.3.0 sidekiq gem)

Stop redirecting rails logger to sidekiq logger inside sidekiq.

---

Gemfile

This way the bootsnap caches are much more likely to be effective.
See https://github.com/Shopify/bootsnap#usage.

Set `require: false` for bootsnap.

---

lib/tasks/support.rake
spec/lib/oidc_client_spec.rb
spec/lib/support_spec.rb
spec/models/logout_notice_spec.rb
spec/requests/back_channel_logout_spec.rb
spec/requests/logout_notice_invalidation_spec.rb
spec/spec_helper.rb
spec/workers/expired_auth_request_worker_spec.rb
spec/workers/expired_sensitive_exception_worker_spec.rb
spec/workers/expired_tombstone_worker_spec.rb

This PR adds 3 new support rake tasks.
`support:delete_user:dry_run['test@example.com']` will simulate deleting a user for the given email address, returning the user's OICD sub for further confirmation.
`support:delete_user:real['test@example.com']` will delete the user.
`support:find_deleted_user_by_oicd_sub['user-id-123`]` will return the time that the user for the given OICD sub was deleted.
[trello](https://trello.com/c/ObbXmXJC/1757-add-rake-task-to-delete-accounts-more-efficiently)

Add support Rake tasks for deleting, and finding deleted, users

---

docs/support/rake_tasks.md

This PR adds some light documentation for the PublishingAPI and user find/delete Rake tasks, so that they appear in the DevDocs for easier info.

Add documentation for Rake tasks

---

app/views/help_pages/sign_in.html.erb

Following the One Login accounts team review of the `/sign-in` page, we have decided to add another visa related link on the page and review it after a month to see if that has any impact on the search term.
In the past quarter the top 4 and 5 page searches were for 'visa' or 'visa application' and users were going to the visa application guidance page. We have added a link to the guidance page on 'How to sign in to continue your visa application', as some supporting data suggests that people are struggling to sign in to complete an unfinished visa application.
https://govukverify.atlassian.net/browse/GUA-838

GUA-838: Add new link to /sign-in page

---

docs/support/rake_tasks.md
lib/tasks/support.rake
spec/lib/support_spec.rb

Email subscriptions get ended when an account is deleted via the API [1], however the manual rake task doesn't include this step. If the subscriber doesn't exist then we'll just return `nil` and continue with the account deletion.
[1]: https://github.com/alphagov/account-api/blob/39af89177ed2ed6380d30f3469e6ab7c86348de2/app/controllers/internal/oidc_users_controller.rb#L31

Delete subscriptions on manually deleting account

---

.github/workflows/ci.yml

Snyk's SCA is failing for no known reason, and it's skipped in some other repos, so remove it for the time being.

Remove failing Snyk SCA tests

---

app/controllers/oidc_events_controller.rb

- in tests, this worked fine. But in practise, there was some odd variable shadowing going on that led to the client logout_token method being called with a nil.
Some details of thse issue:
-  https://gds.slack.com/archives/CADGP8PB4/p1720453623685349 / 
- https://stackoverflow.com/questions/15789540/methods-local-variable-with-same-name-as-another-method
(Basic problem: ruby instantiates local variables instantly and they override class methods, so by declaring a variable logout_token, even on the left hand side, we instantly create that token as nil. Then when it's passed to the variable on the right hand side it has that nil value rather than the one from the method).
⚠️ This repo is Continuously Deployed: make sure you [follow the …

Rename parameter variable

---

app/views/help_pages/sign_in.html.erb

Update text on Sign into Service page.
Remove mention of Government Gateway, as part of move to GOV.UK One Login.

Update Sign into Service page text
